import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatINR(amount: number) {
  return "Rs. " + new Intl.NumberFormat("en-IN").format(amount);
}

export function downloadInvoicePdf(data: {
  invoiceNo: string;
  date: string;
  billTo: string;
  gstin: string;
  items: { desc: string; qty: number; rate: number }[];
}) {
  const doc = new jsPDF();
  const { invoiceNo, date, billTo, gstin, items } = data;

  // Header bar
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 14, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`DoclifyAI`, 196, 12, { align: "right" });
  doc.text(`#${invoiceNo}`, 196, 20, { align: "right" });

  // From / Bill To
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 42);
  doc.text("BILL TO", 110, 42);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("DoclifyAI Business", 14, 49);
  doc.text("Mumbai, Maharashtra", 14, 55);
  doc.text(billTo.replace(/\n/g, ", "), 110, 49, { maxWidth: 80 });
  doc.text(`GSTIN: ${gstin}`, 110, 62);

  // Date
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.text(`Date: ${date}`, 14, 70);

  // Items table
  const subtotal = items.reduce((s, i) => s + i.qty * i.rate, 0);
  const gst = Math.round(subtotal * 0.18);
  const total = subtotal + gst;

  autoTable(doc, {
    startY: 80,
    head: [["#", "Description", "Qty", "Rate", "Amount"]],
    body: [
      ...items.map((item, i) => [
        i + 1,
        item.desc,
        item.qty,
        formatINR(item.rate),
        formatINR(item.qty * item.rate),
      ]),
    ],
    foot: [
      ["", "", "", "Subtotal", formatINR(subtotal)],
      ["", "", "", "GST (18%)", formatINR(gst)],
      ["", "", "", "TOTAL", formatINR(total)],
    ],
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: "bold" },
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42] },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 10 }, 1: { cellWidth: 80 } },
  });

  // Footer
  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Thank you for your business!", 105, finalY, { align: "center" });
  doc.text("Generated by DoclifyAI", 105, finalY + 6, { align: "center" });

  doc.save(`${invoiceNo}.pdf`);
}

async function fetchAsDataUrl(url: string): Promise<string | null> {
  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    const blob = await resp.blob();
    return await new Promise((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(reader.result as string);
      reader.onerror = () => resolve(null);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

export type InvoiceTemplate = "modern" | "minimal" | "professional" | "gst" | "restaurant" | "retail" | "wholesale";

export type AdvancedInvoiceData = {
  invoiceNo: string;
  date: string;
  dueDate?: string;
  poNumber?: string;
  deliveryDate?: string;
  billTo: string;
  gstin: string;
  items: { desc: string; hsn?: string; sku?: string; qty: number; rate: number; gstPercent: number }[];
  fromName: string;
  fromAddress: string;
  fromGst?: string;
  logo?: string | null;
  discountType: "percent" | "flat";
  discountValue: number;
  shipping: number;
  roundOff: boolean;
  taxMode: "cgst-sgst" | "igst";
  notes?: string;
  terms?: string;
  status: string;
  upiId?: string | null;
  signatureDataUrl?: string | null;
  stampDataUrl?: string | null;
  template?: InvoiceTemplate;
};

type Ctx = AdvancedInvoiceData & {
  subtotal: number;
  discount: number;
  taxable: number;
  taxAmount: number;
  total: number;
  cgst: number;
  sgst: number;
  igst: number;
  qrDataUrl: string | null;
};

function buildContext(data: AdvancedInvoiceData, qrDataUrl: string | null): Ctx {
  const subtotal = data.items.reduce((s, i) => s + i.qty * i.rate, 0);
  const discount = data.discountType === "percent" ? subtotal * (data.discountValue / 100) : data.discountValue;
  const taxable = Math.max(0, subtotal - discount);
  const taxAmount = data.items.reduce((s, i) => {
    const lineTaxable = i.qty * i.rate * (taxable / Math.max(subtotal, 1));
    return s + lineTaxable * (i.gstPercent / 100);
  }, 0);
  const beforeRound = taxable + taxAmount + data.shipping;
  const total = data.roundOff ? Math.round(beforeRound) : Math.round(beforeRound * 100) / 100;
  return {
    ...data,
    subtotal, discount, taxable, taxAmount, total,
    cgst: data.taxMode === "cgst-sgst" ? taxAmount / 2 : 0,
    sgst: data.taxMode === "cgst-sgst" ? taxAmount / 2 : 0,
    igst: data.taxMode === "igst" ? taxAmount : 0,
    qrDataUrl,
  };
}

function drawSignatureBlock(doc: jsPDF, ctx: Ctx, sigY: number) {
  if (ctx.stampDataUrl) {
    try { doc.addImage(ctx.stampDataUrl, "PNG", 150, sigY - 18, 22, 22); } catch { /* ignore */ }
  }
  if (ctx.signatureDataUrl) {
    try { doc.addImage(ctx.signatureDataUrl, "PNG", 150, sigY, 45, 14); } catch { /* ignore */ }
  }
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.line(150, sigY + 16, 196, sigY + 16);
  doc.text("Authorised Signatory", 173, sigY + 21, { align: "center" });
}

function drawQrBlock(doc: jsPDF, ctx: Ctx, x: number, y: number) {
  if (!ctx.qrDataUrl) return;
  try {
    doc.addImage(ctx.qrDataUrl, "PNG", x, y, 26, 26);
    doc.setFontSize(7);
    doc.setTextColor(100, 100, 100);
    doc.text("Scan to pay via UPI", x + 13, y + 30, { align: "center" });
  } catch { /* ignore malformed image */ }
}

function summaryLines(ctx: Ctx): [string, string][] {
  const lines: [string, string][] = [["Subtotal", formatINR(ctx.subtotal)]];
  if (ctx.discount > 0) lines.push([`Discount${ctx.discountType === "percent" ? ` (${ctx.discountValue}%)` : ""}`, `- ${formatINR(ctx.discount)}`]);
  if (ctx.taxMode === "cgst-sgst") {
    lines.push(["CGST", formatINR(ctx.cgst)]);
    lines.push(["SGST", formatINR(ctx.sgst)]);
  } else {
    lines.push(["IGST", formatINR(ctx.igst)]);
  }
  if (ctx.shipping > 0) lines.push(["Shipping", formatINR(ctx.shipping)]);
  lines.push(["TOTAL", formatINR(ctx.total)]);
  return lines;
}

/* ── Modern: dark header bar, blue accents (original design) ─────────────── */
function renderModern(doc: jsPDF, ctx: Ctx) {
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");
  if (ctx.logo) {
    try { doc.addImage(ctx.logo, "PNG", 14, 5, 18, 18); } catch { /* ignore */ }
  }
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", ctx.logo ? 36 : 14, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`#${ctx.invoiceNo}`, 196, 12, { align: "right" });
  doc.text(`Status: ${ctx.status.toUpperCase()}`, 196, 20, { align: "right" });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 42);
  doc.text("BILL TO", 110, 42);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(ctx.fromName, 14, 49);
  doc.text(ctx.fromAddress, 14, 55, { maxWidth: 85 });
  if (ctx.fromGst) doc.text(`GSTIN: ${ctx.fromGst}`, 14, 61);
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 49, { maxWidth: 80 });
  doc.text(`GSTIN: ${ctx.gstin || "—"}`, 110, 62);

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  const metaParts = [`Date: ${ctx.date}`];
  if (ctx.dueDate) metaParts.push(`Due: ${ctx.dueDate}`);
  if (ctx.poNumber) metaParts.push(`PO#: ${ctx.poNumber}`);
  if (ctx.deliveryDate) metaParts.push(`Delivery: ${ctx.deliveryDate}`);
  doc.text(metaParts.join("   |   "), 14, 72);

  autoTable(doc, {
    startY: 78,
    head: [["#", "Description", "HSN", "Qty", "Rate", "GST%", "Amount"]],
    body: ctx.items.map((item, i) => [
      i + 1, item.desc, item.hsn || "—", item.qty, formatINR(item.rate), `${item.gstPercent}%`,
      formatINR(item.qty * item.rate),
    ]),
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 60 } },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFontSize(9);
  for (const [label, value] of summaryLines(ctx)) {
    const isTotal = label === "TOTAL";
    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 15 : 100, isTotal ? 23 : 100, isTotal ? 42 : 100);
    doc.text(label, 150, y, { align: "right" });
    doc.text(value, 196, y, { align: "right" });
    y += 6;
  }
  y += 6;

  drawQrBlock(doc, ctx, 14, y);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  if (ctx.notes) {
    doc.setFont("helvetica", "bold");
    doc.text("Notes:", 70, textY);
    doc.setFont("helvetica", "normal");
    doc.text(ctx.notes, 70, textY + 5, { maxWidth: 60 });
    textY += 16;
  }
  if (ctx.terms) {
    doc.setFont("helvetica", "bold");
    doc.text("Terms & Conditions:", 70, textY);
    doc.setFont("helvetica", "normal");
    doc.text(ctx.terms, 70, textY + 5, { maxWidth: 60 });
  }

  drawSignatureBlock(doc, ctx, Math.max(y + 35, textY + 20));

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, 285, { align: "center" });
}

/* ── Minimal: plain white, thin rules, no color blocks ────────────────────── */
function renderMinimal(doc: jsPDF, ctx: Ctx) {
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(20);
  doc.setFont("helvetica", "normal");
  doc.text("Invoice", 14, 22);
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text(`#${ctx.invoiceNo}`, 196, 16, { align: "right" });
  doc.text(`${ctx.date}`, 196, 22, { align: "right" });
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 28, 196, 28);

  if (ctx.logo) {
    try { doc.addImage(ctx.logo, "PNG", 170, 8, 16, 16); } catch { /* ignore */ }
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("FROM", 14, 38);
  doc.text("BILL TO", 110, 38);
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(ctx.fromName, 14, 44);
  doc.text(ctx.fromAddress, 14, 49, { maxWidth: 85 });
  if (ctx.fromGst) doc.text(`GSTIN ${ctx.fromGst}`, 14, 54);
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 44, { maxWidth: 80 });
  if (ctx.gstin) doc.text(`GSTIN ${ctx.gstin}`, 110, 54);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const metaParts = [];
  if (ctx.dueDate) metaParts.push(`Due ${ctx.dueDate}`);
  if (ctx.poNumber) metaParts.push(`PO ${ctx.poNumber}`);
  if (ctx.deliveryDate) metaParts.push(`Delivery ${ctx.deliveryDate}`);
  if (metaParts.length) doc.text(metaParts.join("    "), 14, 62);

  autoTable(doc, {
    startY: 68,
    head: [["Description", "Qty", "Rate", "Amount"]],
    body: ctx.items.map((item) => [item.desc, item.qty, formatINR(item.rate), formatINR(item.qty * item.rate)]),
    headStyles: { fillColor: [255, 255, 255], textColor: [120, 120, 120], fontStyle: "normal", lineWidth: 0 },
    bodyStyles: { textColor: [60, 60, 60] },
    styles: { fontSize: 9, lineColor: [230, 230, 230] },
    theme: "plain",
    columnStyles: { 0: { cellWidth: 100 } },
    didDrawPage: () => {
      doc.setDrawColor(220, 220, 220);
    },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;
  doc.setDrawColor(220, 220, 220);
  doc.line(120, y, 196, y);
  y += 6;
  doc.setFontSize(9);
  for (const [label, value] of summaryLines(ctx)) {
    const isTotal = label === "TOTAL";
    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 15 : 130, isTotal ? 23 : 130, isTotal ? 42 : 130);
    doc.text(label, 150, y, { align: "right" });
    doc.text(value, 196, y, { align: "right" });
    y += 6;
  }
  y += 6;

  drawQrBlock(doc, ctx, 14, y);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  if (ctx.notes) { doc.text(`Notes: ${ctx.notes}`, 14, textY, { maxWidth: 90 }); textY += 12; }
  if (ctx.terms) { doc.text(`Terms: ${ctx.terms}`, 14, textY, { maxWidth: 90 }); }

  if (ctx.signatureDataUrl) {
    try { doc.addImage(ctx.signatureDataUrl, "PNG", 150, y, 45, 14); } catch { /* ignore */ }
  }
  doc.setDrawColor(200, 200, 200);
  doc.line(150, y + 16, 196, y + 16);
  doc.setFontSize(8);
  doc.text("Authorised Signatory", 173, y + 21, { align: "center" });

  doc.setFontSize(7);
  doc.setTextColor(180, 180, 180);
  doc.text("Generated by DoclifyAI", 105, 290, { align: "center" });
}

/* ── Professional: navy/charcoal, serif headings, formal layout ───────────── */
function renderProfessional(doc: jsPDF, ctx: Ctx) {
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(1.2);
  doc.line(14, 16, 196, 16);
  if (ctx.logo) {
    try { doc.addImage(ctx.logo, "PNG", 14, 20, 16, 16); } catch { /* ignore */ }
  }
  doc.setTextColor(30, 41, 59);
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.text("INVOICE", 196, 28, { align: "right" });
  doc.setFont("times", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`No. ${ctx.invoiceNo}   ·   ${ctx.date}   ·   ${ctx.status.toUpperCase()}`, 196, 36, { align: "right" });

  doc.setDrawColor(220, 220, 220);
  doc.line(14, 44, 196, 44);

  doc.setFont("times", "bold");
  doc.setFontSize(9);
  doc.setTextColor(30, 41, 59);
  doc.text("BILLED FROM", 14, 54);
  doc.text("BILLED TO", 110, 54);
  doc.setFont("times", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(ctx.fromName, 14, 61);
  doc.text(ctx.fromAddress, 14, 67, { maxWidth: 85 });
  if (ctx.fromGst) doc.text(`GSTIN: ${ctx.fromGst}`, 14, 73);
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 61, { maxWidth: 80 });
  if (ctx.gstin) doc.text(`GSTIN: ${ctx.gstin}`, 110, 73);

  const metaParts = [];
  if (ctx.dueDate) metaParts.push(`Due: ${ctx.dueDate}`);
  if (ctx.poNumber) metaParts.push(`PO#: ${ctx.poNumber}`);
  if (ctx.deliveryDate) metaParts.push(`Delivery: ${ctx.deliveryDate}`);
  if (metaParts.length) {
    doc.setFontSize(8);
    doc.text(metaParts.join("   |   "), 14, 82);
  }

  autoTable(doc, {
    startY: 88,
    head: [["#", "Description", "HSN", "Qty", "Rate", "GST%", "Amount"]],
    body: ctx.items.map((item, i) => [
      i + 1, item.desc, item.hsn || "—", item.qty, formatINR(item.rate), `${item.gstPercent}%`,
      formatINR(item.qty * item.rate),
    ]),
    headStyles: { fillColor: [30, 41, 59], textColor: 255, fontStyle: "bold", font: "times" },
    bodyStyles: { font: "times" },
    styles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 60 } },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFont("times", "normal");
  doc.setFontSize(9);
  for (const [label, value] of summaryLines(ctx)) {
    const isTotal = label === "TOTAL";
    doc.setFont("times", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 30 : 100, isTotal ? 41 : 100, isTotal ? 59 : 100);
    doc.text(label, 150, y, { align: "right" });
    doc.text(value, 196, y, { align: "right" });
    y += 6;
  }
  y += 6;

  drawQrBlock(doc, ctx, 14, y);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  if (ctx.notes) { doc.setFont("times", "bold"); doc.text("Notes:", 70, textY); doc.setFont("times", "normal"); doc.text(ctx.notes, 70, textY + 5, { maxWidth: 60 }); textY += 16; }
  if (ctx.terms) { doc.setFont("times", "bold"); doc.text("Terms & Conditions:", 70, textY); doc.setFont("times", "normal"); doc.text(ctx.terms, 70, textY + 5, { maxWidth: 60 }); }

  drawSignatureBlock(doc, ctx, Math.max(y + 35, textY + 20));

  doc.setFont("times", "italic");
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, 285, { align: "center" });
}

/* ── GST: India-specific layout, prominent tax summary box ─────────────────── */
function renderGst(doc: jsPDF, ctx: Ctx) {
  doc.setFillColor(4, 120, 87);
  doc.rect(0, 0, 210, 26, "F");
  if (ctx.logo) {
    try { doc.addImage(ctx.logo, "PNG", 14, 4, 18, 18); } catch { /* ignore */ }
  }
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("TAX INVOICE", ctx.logo ? 36 : 14, 17);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`#${ctx.invoiceNo}`, 196, 11, { align: "right" });
  doc.text(`${ctx.date}`, 196, 17, { align: "right" });
  doc.text(`${ctx.status.toUpperCase()}`, 196, 23, { align: "right" });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("SUPPLIER", 14, 36);
  doc.text("RECIPIENT", 110, 36);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(ctx.fromName, 14, 43);
  doc.text(ctx.fromAddress, 14, 48, { maxWidth: 85 });
  doc.setFont("helvetica", "bold");
  doc.text(`GSTIN: ${ctx.fromGst || "—"}`, 14, 54);
  doc.setFont("helvetica", "normal");
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 43, { maxWidth: 80 });
  doc.setFont("helvetica", "bold");
  doc.text(`GSTIN: ${ctx.gstin || "—"}`, 110, 54);

  const metaParts = [];
  if (ctx.dueDate) metaParts.push(`Due: ${ctx.dueDate}`);
  if (ctx.poNumber) metaParts.push(`PO#: ${ctx.poNumber}`);
  if (ctx.deliveryDate) metaParts.push(`Delivery: ${ctx.deliveryDate}`);
  if (metaParts.length) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(metaParts.join("   |   "), 14, 62);
  }

  autoTable(doc, {
    startY: 68,
    head: [["#", "Description", "HSN/SAC", "Qty", "Rate", "Taxable", "GST%", "Amount"]],
    body: ctx.items.map((item, i) => {
      const lineSubtotal = item.qty * item.rate;
      return [i + 1, item.desc, item.hsn || "—", item.qty, formatINR(item.rate), formatINR(lineSubtotal), `${item.gstPercent}%`, formatINR(lineSubtotal)];
    }),
    headStyles: { fillColor: [4, 120, 87], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 7.5 },
    columnStyles: { 0: { cellWidth: 7 }, 1: { cellWidth: 45 } },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 6;

  // Prominent tax summary box
  doc.setFillColor(240, 253, 244);
  doc.setDrawColor(4, 120, 87);
  doc.roundedRect(120, y, 76, ctx.taxMode === "cgst-sgst" ? 42 : 36, 2, 2, "FD");
  let boxY = y + 7;
  doc.setFontSize(8);
  doc.setTextColor(4, 120, 87);
  doc.setFont("helvetica", "bold");
  doc.text("TAX SUMMARY", 124, boxY);
  boxY += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  doc.text("Taxable Value", 124, boxY); doc.text(formatINR(ctx.taxable), 192, boxY, { align: "right" }); boxY += 5.5;
  if (ctx.taxMode === "cgst-sgst") {
    doc.text("CGST", 124, boxY); doc.text(formatINR(ctx.cgst), 192, boxY, { align: "right" }); boxY += 5.5;
    doc.text("SGST", 124, boxY); doc.text(formatINR(ctx.sgst), 192, boxY, { align: "right" }); boxY += 5.5;
  } else {
    doc.text("IGST", 124, boxY); doc.text(formatINR(ctx.igst), 192, boxY, { align: "right" }); boxY += 5.5;
  }
  if (ctx.shipping > 0) { doc.text("Shipping", 124, boxY); doc.text(formatINR(ctx.shipping), 192, boxY, { align: "right" }); boxY += 5.5; }
  doc.setFont("helvetica", "bold");
  doc.setTextColor(4, 120, 87);
  doc.text("TOTAL", 124, boxY); doc.text(formatINR(ctx.total), 192, boxY, { align: "right" });

  y += (ctx.taxMode === "cgst-sgst" ? 42 : 36) + 8;

  drawQrBlock(doc, ctx, 14, y - 30);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "normal");
  if (ctx.notes) { doc.setFont("helvetica", "bold"); doc.text("Notes:", 14, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.notes, 14, textY + 5, { maxWidth: 90 }); textY += 16; }
  if (ctx.terms) { doc.setFont("helvetica", "bold"); doc.text("Terms & Conditions:", 14, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.terms, 14, textY + 5, { maxWidth: 90 }); }

  drawSignatureBlock(doc, ctx, Math.max(y, textY + 18));

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, 285, { align: "center" });
}

/* ── Restaurant: narrow receipt-style, centered, friendly footer ──────────── */
function renderRestaurant(doc: jsPDF, ctx: Ctx) {
  const cx = 105;
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(ctx.fromName, cx, 18, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(ctx.fromAddress, cx, 24, { align: "center" });
  if (ctx.fromGst) doc.text(`GSTIN: ${ctx.fromGst}`, cx, 29, { align: "center" });

  doc.setDrawColor(180, 180, 180);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(20, 34, 190, 34);
  doc.setLineDashPattern([], 0);

  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  doc.text(`Bill No: ${ctx.invoiceNo}`, cx, 41, { align: "center" });
  doc.text(`${ctx.date}`, cx, 46, { align: "center" });
  if (ctx.billTo) doc.text(ctx.billTo.replace(/\n/g, ", "), cx, 51, { align: "center", maxWidth: 160 });

  doc.setDrawColor(180, 180, 180);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(20, 56, 190, 56);
  doc.setLineDashPattern([], 0);

  autoTable(doc, {
    startY: 60,
    head: [["Item", "Qty", "Amount"]],
    body: ctx.items.map((item) => [item.desc, item.qty, formatINR(item.qty * item.rate)]),
    theme: "plain",
    headStyles: { textColor: [60, 60, 60], fontStyle: "bold", halign: "center" },
    bodyStyles: { halign: "center" },
    styles: { fontSize: 9, font: "courier" },
    margin: { left: 30, right: 30 },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 4;
  doc.setDrawColor(180, 180, 180);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(20, y, 190, y);
  doc.setLineDashPattern([], 0);
  y += 6;

  doc.setFont("courier", "normal");
  doc.setFontSize(9);
  for (const [label, value] of summaryLines(ctx)) {
    const isTotal = label === "TOTAL";
    doc.setFont("courier", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 15 : 100, isTotal ? 23 : 100, isTotal ? 42 : 100);
    doc.text(label, 75, y, { align: "right" });
    doc.text(value, 135, y, { align: "right" });
    y += 6;
  }
  y += 8;

  drawQrBlock(doc, ctx, cx - 13, y);
  y += 36;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  doc.text("Thank you for dining with us!", cx, y, { align: "center" });
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", cx, y + 8, { align: "center" });
}

/* ── Retail: SKU/barcode-oriented price-list style ─────────────────────────── */
function renderRetail(doc: jsPDF, ctx: Ctx) {
  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, 210, 24, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("RETAIL INVOICE", 14, 16);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`#${ctx.invoiceNo}  ·  ${ctx.date}`, 196, 16, { align: "right" });

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("STORE", 14, 34);
  doc.text("CUSTOMER", 110, 34);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(ctx.fromName, 14, 40);
  doc.text(ctx.fromAddress, 14, 45, { maxWidth: 85 });
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 40, { maxWidth: 80 });

  autoTable(doc, {
    startY: 56,
    head: [["SKU", "Item", "Qty", "Unit Price", "Amount"]],
    body: ctx.items.map((item) => [
      item.sku || item.hsn || "—", item.desc, item.qty, formatINR(item.rate), formatINR(item.qty * item.rate),
    ]),
    headStyles: { fillColor: [124, 58, 237], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 26, font: "courier" }, 1: { cellWidth: 60 } },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFontSize(9);
  for (const [label, value] of summaryLines(ctx)) {
    const isTotal = label === "TOTAL";
    doc.setFont("helvetica", isTotal ? "bold" : "normal");
    doc.setTextColor(isTotal ? 124 : 100, isTotal ? 58 : 100, isTotal ? 237 : 100);
    doc.text(label, 150, y, { align: "right" });
    doc.text(value, 196, y, { align: "right" });
    y += 6;
  }
  y += 6;

  drawQrBlock(doc, ctx, 14, y);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  if (ctx.notes) { doc.setFont("helvetica", "bold"); doc.text("Notes:", 70, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.notes, 70, textY + 5, { maxWidth: 60 }); textY += 16; }
  if (ctx.terms) { doc.setFont("helvetica", "bold"); doc.text("Exchange/Return Policy:", 70, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.terms, 70, textY + 5, { maxWidth: 60 }); }

  drawSignatureBlock(doc, ctx, Math.max(y + 35, textY + 20));

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, 285, { align: "center" });
}

/* ── Wholesale: bulk-quantity & per-unit pricing emphasis ──────────────────── */
function renderWholesale(doc: jsPDF, ctx: Ctx) {
  doc.setFillColor(217, 119, 6);
  doc.rect(0, 0, 210, 8, "F");
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("WHOLESALE INVOICE", 14, 24);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`#${ctx.invoiceNo}  ·  ${ctx.date}  ·  Bulk Order`, 14, 31);
  doc.text(`Status: ${ctx.status.toUpperCase()}`, 196, 24, { align: "right" });

  doc.setDrawColor(217, 119, 6);
  doc.setLineWidth(0.8);
  doc.line(14, 36, 196, 36);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("SUPPLIER", 14, 44);
  doc.text("BUYER", 110, 44);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text(ctx.fromName, 14, 50);
  doc.text(ctx.fromAddress, 14, 55, { maxWidth: 85 });
  if (ctx.fromGst) doc.text(`GSTIN: ${ctx.fromGst}`, 14, 60);
  doc.text(ctx.billTo.replace(/\n/g, ", "), 110, 50, { maxWidth: 80 });
  if (ctx.gstin) doc.text(`GSTIN: ${ctx.gstin}`, 110, 60);

  autoTable(doc, {
    startY: 68,
    head: [["#", "Item", "Bulk Qty", "Unit", "Rate/Unit", "GST%", "Total"]],
    body: ctx.items.map((item, i) => [
      i + 1, item.desc, item.qty, "units", formatINR(item.rate), `${item.gstPercent}%`, formatINR(item.qty * item.rate),
    ]),
    headStyles: { fillColor: [217, 119, 6], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 8 },
    columnStyles: { 0: { cellWidth: 8 }, 1: { cellWidth: 55 } },
  });

  let y = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 8;
  doc.setFillColor(255, 251, 235);
  doc.setDrawColor(217, 119, 6);
  doc.roundedRect(120, y, 76, ctx.discount > 0 ? 38 : 32, 2, 2, "FD");
  let boxY = y + 7;
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(217, 119, 6);
  doc.text("ORDER SUMMARY", 124, boxY);
  boxY += 6;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(60, 60, 60);
  const totalUnits = ctx.items.reduce((s, i) => s + i.qty, 0);
  doc.text("Total Units", 124, boxY); doc.text(String(totalUnits), 192, boxY, { align: "right" }); boxY += 5.5;
  doc.text("Subtotal", 124, boxY); doc.text(formatINR(ctx.subtotal), 192, boxY, { align: "right" }); boxY += 5.5;
  if (ctx.discount > 0) { doc.text("Bulk Discount", 124, boxY); doc.text(`- ${formatINR(ctx.discount)}`, 192, boxY, { align: "right" }); boxY += 5.5; }
  doc.text("Tax", 124, boxY); doc.text(formatINR(ctx.taxAmount), 192, boxY, { align: "right" }); boxY += 5.5;
  doc.setFont("helvetica", "bold");
  doc.setTextColor(217, 119, 6);
  doc.text("TOTAL", 124, boxY); doc.text(formatINR(ctx.total), 192, boxY, { align: "right" });

  y += (ctx.discount > 0 ? 38 : 32) + 8;
  drawQrBlock(doc, ctx, 14, y - 30);

  let textY = y;
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "normal");
  if (ctx.notes) { doc.setFont("helvetica", "bold"); doc.text("Notes:", 14, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.notes, 14, textY + 5, { maxWidth: 90 }); textY += 16; }
  if (ctx.terms) { doc.setFont("helvetica", "bold"); doc.text("Payment Terms:", 14, textY); doc.setFont("helvetica", "normal"); doc.text(ctx.terms, 14, textY + 5, { maxWidth: 90 }); }

  drawSignatureBlock(doc, ctx, Math.max(y, textY + 18));

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, 285, { align: "center" });
}

/** Richer invoice PDF supporting tax breakdown, discounts, signature/stamp, QR code, and multiple visual templates. */
export async function downloadInvoicePdfAdvanced(data: AdvancedInvoiceData) {
  const doc = new jsPDF();
  let qrDataUrl: string | null = null;
  if (data.upiId) {
    const subtotalForTotal = data.items.reduce((s, i) => s + i.qty * i.rate, 0);
    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=120x120&data=${encodeURIComponent(`upi://pay?pa=${data.upiId}&am=${subtotalForTotal.toFixed(2)}&cu=INR&tn=Invoice ${data.invoiceNo}`)}`;
    qrDataUrl = await fetchAsDataUrl(qrUrl);
  }
  const ctx = buildContext(data, qrDataUrl);

  switch (data.template) {
    case "minimal":
      renderMinimal(doc, ctx);
      break;
    case "professional":
      renderProfessional(doc, ctx);
      break;
    case "gst":
      renderGst(doc, ctx);
      break;
    case "restaurant":
      renderRestaurant(doc, ctx);
      break;
    case "retail":
      renderRetail(doc, ctx);
      break;
    case "wholesale":
      renderWholesale(doc, ctx);
      break;
    default:
      renderModern(doc, ctx);
  }

  doc.save(`${data.invoiceNo}.pdf`);
}

export function downloadChallanPdf(data: {
  challanNo: string;
  date: string;
  deliverTo: string;
  vehicle: string;
  items: { desc: string; qty: number; unit: string }[];
  fromName?: string;
  fromAddress?: string;
  signatureDataUrl?: string | null;
}) {
  const doc = new jsPDF();
  const {
    challanNo, date, deliverTo, vehicle, items,
    fromName = "DoclifyAI Business",
    fromAddress = "Mumbai",
    signatureDataUrl,
  } = data;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("DELIVERY CHALLAN", 14, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`#${challanNo}`, 196, 20, { align: "right" });

  // Details
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 42);
  doc.text("DELIVER TO", 110, 42);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`${fromName}, ${fromAddress}`, 14, 49);
  doc.text(deliverTo.replace(/\n/g, ", "), 110, 49, { maxWidth: 80 });

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.text(`Date: ${date}  |  Vehicle No: ${vehicle}`, 14, 70);

  // Items table
  autoTable(doc, {
    startY: 80,
    head: [["#", "Item Description", "Quantity", "Unit"]],
    body: items.map((item, i) => [i + 1, item.desc, item.qty, item.unit]),
    headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 10 }, 1: { cellWidth: 100 } },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  // Signatures
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("Receiver's Signature", 30, finalY, { align: "center" });
  doc.text("Authorised Signatory", 180, finalY, { align: "center" });
  if (signatureDataUrl) {
    try {
      doc.addImage(signatureDataUrl, "PNG", 155, finalY - 14, 50, 13);
    } catch {
      /* ignore malformed image data */
    }
  }
  doc.line(10, finalY + 15, 60, finalY + 15);
  doc.line(155, finalY + 15, 205, finalY + 15);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by DoclifyAI", 105, finalY + 28, { align: "center" });

  doc.save(`${challanNo}.pdf`);
}
