import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

function formatINR(amount: number) {
  return "Rs. " + new Intl.NumberFormat("en-IN").format(amount);
}

export function downloadInvoicePdf(data: {
  invoiceNo: string;
  date: string;
  billTo: string;
  gstin: string;
  items: { desc: string; qty: number; rate: number }[];
}) {
  const doc = new jsPDF();
  const { invoiceNo, date, billTo, gstin, items } = data;

  // Header bar
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", 14, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`ConvertAI`, 196, 12, { align: "right" });
  doc.text(`#${invoiceNo}`, 196, 20, { align: "right" });

  // From / Bill To
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 42);
  doc.text("BILL TO", 110, 42);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("ConvertAI Business", 14, 49);
  doc.text("Mumbai, Maharashtra", 14, 55);
  doc.text(billTo.replace(/\n/g, ", "), 110, 49, { maxWidth: 80 });
  doc.text(`GSTIN: ${gstin}`, 110, 62);

  // Date
  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.text(`Date: ${date}`, 14, 70);

  // Items table
  const subtotal = items.reduce((s, i) => s + i.qty * i.rate, 0);
  const gst = Math.round(subtotal * 0.18);
  const total = subtotal + gst;

  autoTable(doc, {
    startY: 80,
    head: [["#", "Description", "Qty", "Rate", "Amount"]],
    body: [
      ...items.map((item, i) => [
        i + 1,
        item.desc,
        item.qty,
        formatINR(item.rate),
        formatINR(item.qty * item.rate),
      ]),
    ],
    foot: [
      ["", "", "", "Subtotal", formatINR(subtotal)],
      ["", "", "", "GST (18%)", formatINR(gst)],
      ["", "", "", "TOTAL", formatINR(total)],
    ],
    headStyles: { fillColor: [59, 130, 246], textColor: 255, fontStyle: "bold" },
    footStyles: { fillColor: [241, 245, 249], textColor: [15, 23, 42] },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 10 }, 1: { cellWidth: 80 } },
  });

  // Footer
  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Thank you for your business!", 105, finalY, { align: "center" });
  doc.text("Generated by ConvertAI · adityasingh018adi@gmail.com", 105, finalY + 6, { align: "center" });

  doc.save(`${invoiceNo}.pdf`);
}

export function downloadChallanPdf(data: {
  challanNo: string;
  date: string;
  deliverTo: string;
  vehicle: string;
  items: { desc: string; qty: number; unit: string }[];
}) {
  const doc = new jsPDF();
  const { challanNo, date, deliverTo, vehicle, items } = data;

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 30, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("DELIVERY CHALLAN", 14, 20);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`#${challanNo}`, 196, 20, { align: "right" });

  // Details
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, 42);
  doc.text("DELIVER TO", 110, 42);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text("ConvertAI Business, Mumbai", 14, 49);
  doc.text(deliverTo.replace(/\n/g, ", "), 110, 49, { maxWidth: 80 });

  doc.setTextColor(15, 23, 42);
  doc.setFont("helvetica", "bold");
  doc.text(`Date: ${date}  |  Vehicle No: ${vehicle}`, 14, 70);

  // Items table
  autoTable(doc, {
    startY: 80,
    head: [["#", "Item Description", "Quantity", "Unit"]],
    body: items.map((item, i) => [i + 1, item.desc, item.qty, item.unit]),
    headStyles: { fillColor: [245, 158, 11], textColor: 255, fontStyle: "bold" },
    styles: { fontSize: 9 },
    columnStyles: { 0: { cellWidth: 10 }, 1: { cellWidth: 100 } },
  });

  const finalY = (doc as jsPDF & { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 20;

  // Signatures
  doc.setFontSize(9);
  doc.setTextColor(15, 23, 42);
  doc.text("Receiver's Signature", 30, finalY, { align: "center" });
  doc.text("Authorised Signatory", 180, finalY, { align: "center" });
  doc.line(10, finalY + 15, 60, finalY + 15);
  doc.line(155, finalY + 15, 205, finalY + 15);

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by ConvertAI · adityasingh018adi@gmail.com", 105, finalY + 28, { align: "center" });

  doc.save(`${challanNo}.pdf`);
}
